# Generated by Django 4.0.5 on 2022-06-30 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='access_interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.IntegerField()),
                ('who_can_initiate', models.CharField(choices=[('bot', 'BOT'), ('user', 'USER')], default='bot', max_length=10)),
                ('expiry_date', models.DateTimeField()),
                ('track', models.CharField(choices=[('learn', 'LEARN'), ('hire', 'HIRE')], default='learn', max_length=10)),
                ('collect_email', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=10)),
                ('collect_candidate_id', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=10)),
                ('candidate_feedback_message', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=10)),
                ('voice_match', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=10)),
                ('collect_resume', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='bot_messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('welcome_msg', models.CharField(max_length=500)),
                ('instruction_msg', models.CharField(max_length=500)),
                ('completion_msg', models.CharField(max_length=500)),
                ('warning_msg', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='create_interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('position_code', models.IntegerField()),
                ('job_title', models.CharField(max_length=100)),
                ('total_questions', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='interview_notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_sent_to_user', models.CharField(choices=[('yes', 'YES'), ('no', 'NO')], default='yes', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='parent_core_scores_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField(max_length=100)),
                ('candidate_name', models.CharField(max_length=100)),
                ('access_id', models.IntegerField(max_length=100)),
                ('resume_score', models.IntegerField(max_length=100)),
                ('pace', models.IntegerField(max_length=100)),
                ('power_words', models.CharField(max_length=100)),
                ('value_scale', models.IntegerField(max_length=100)),
                ('pitch_range', models.IntegerField(max_length=100)),
                ('gesture', models.CharField(max_length=100)),
                ('overall_sentiment_score', models.IntegerField(max_length=100)),
                ('overall_content', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='report_sent_to_email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('interview_notification_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_Backend.interview_notification')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=500)),
                ('ideal_ans', models.CharField(max_length=500)),
                ('ans_format', models.CharField(max_length=500)),
                ('create_interview_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_Backend.create_interview')),
            ],
        ),
        migrations.CreateModel(
            name='interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_interview_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_Backend.access_interview')),
                ('bot_messages_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_Backend.bot_messages')),
                ('create_interview_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_Backend.create_interview')),
                ('interview_notification_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_Backend.interview_notification')),
            ],
        ),
        migrations.CreateModel(
            name='chlid_scores_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField(max_length=100)),
                ('candidate_name', models.CharField(max_length=100)),
                ('access_id', models.IntegerField(max_length=100)),
                ('Question_No', models.IntegerField(max_length=100)),
                ('Likeability', models.IntegerField(max_length=100)),
                ('Charm', models.CharField(max_length=100)),
                ('Confidence', models.IntegerField(max_length=100)),
                ('Fluency', models.IntegerField(max_length=100)),
                ('Content', models.CharField(max_length=100)),
                ('Overall', models.IntegerField(max_length=100)),
                ('parent_core_scores_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_Backend.parent_core_scores_db')),
            ],
        ),
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('slack', 'SLACK'), ('whatsapp', 'WHATSAPP'), ('telegram', 'TELEGRAM')], default='slack', max_length=10)),
                ('access_interview_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_Backend.access_interview')),
            ],
        ),
    ]
