# Generated by Django 4.0.5 on 2022-06-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions_database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_code', models.IntegerField(max_length=100)),
                ('who_can_initiate', models.CharField(max_length=100)),
                ('expiry_date', models.DateField(default='Today')),
                ('phone_number', models.IntegerField(max_length=10)),
                ('track', models.CharField(max_length=100)),
                ('collect_email', models.BooleanField(default=True)),
                ('collect_candidate_id', models.BooleanField(default=True)),
                ('company', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('postion_code', models.IntegerField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('report_sent_to_user', models.BooleanField(default=True)),
                ('channel_field1', models.CharField(max_length=100)),
                ('channel_field2', models.CharField(max_length=100)),
                ('channel_field3', models.CharField(max_length=100)),
                ('candidate_id', models.IntegerField(max_length=100)),
                ('candidate_feedback_message', models.CharField(max_length=100)),
                ('voice_match', models.BooleanField(default=True)),
                ('hiring_email1', models.CharField(max_length=100)),
                ('hiring_email2', models.CharField(max_length=100)),
                ('interaction_welcome', models.CharField(max_length=100)),
                ('interaction_instruction', models.CharField(max_length=100)),
                ('interaction_completion_message', models.CharField(max_length=100)),
                ('bot_error_message', models.CharField(max_length=100)),
                ('collect_resume', models.BooleanField(default=True)),
                ('total_question', models.IntegerField(max_length=10)),
                ('questions', models.CharField(max_length=1000)),
                ('answer_format', models.CharField(max_length=100)),
                ('ideal_answers', models.CharField(max_length=1000)),
                ('candidate_answers', models.CharField(max_length=1000)),
            ],
        ),
    ]
