# Generated by Django 4.0.5 on 2022-06-28 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_Backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='parent_core_scores_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.IntegerField(max_length=100)),
                ('candidate_name', models.CharField(max_length=100)),
                ('access_id', models.IntegerField(max_length=100)),
                ('resume_score', models.IntegerField(max_length=100)),
                ('pace', models.IntegerField(max_length=100)),
                ('power_words', models.CharField(max_length=100)),
                ('value_scale', models.IntegerField(max_length=100)),
                ('pitch_range', models.IntegerField(max_length=100)),
                ('gesture', models.CharField(max_length=100)),
                ('overall_sentiment_score', models.IntegerField(max_length=100)),
                ('overall_content', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Questions_database',
        ),
    ]
